import type { FruitId } from "./fruits";

export type RoundId = FruitId | "harvest";

export interface Question {
  id: string;
  fruit: RoundId;
  prompt: string;
  options: string[];
  answer: number;
  note: string;
  reference: string;
}

export const QUESTIONS: Question[] = [
  /* ─────────────── LOVE ─────────────── */
  {
    id: "love-1",
    fruit: "love",
    prompt: "\u201CGreater love has no one than this: to lay down one\u2019s ___ for one\u2019s friends.\u201D",
    options: ["life", "crown", "sword", "harvest"],
    answer: 0,
    note: "Jesus spoke this the night before the cross, naming the highest measure of love.",
    reference: "John 15:13",
  },
  {
    id: "love-2",
    fruit: "love",
    prompt: "1 Corinthians 13 opens: \u201CLove is patient, love is ___.\u201D",
    options: ["gentle", "kind", "humble", "faithful"],
    answer: 1,
    note: "Paul begins his portrait of love with two verbs before any adjective: it waits, and it acts kindly.",
    reference: "1 Corinthians 13:4",
  },
  {
    id: "love-3",
    fruit: "love",
    prompt: "Which letter declares plainly that \u201CGod is love\u201D?",
    options: ["James", "1 John", "Titus", "Jude"],
    answer: 1,
    note: "John writes it twice in one chapter \u2014 love is not merely what God does, it is who He is.",
    reference: "1 John 4:8, 16",
  },
  {
    id: "love-4",
    fruit: "love",
    prompt: "In Matthew 22, the greatest commandment is to love God with all your heart, soul and ___.",
    options: ["mind", "silver", "days", "voice"],
    answer: 0,
    note: "Jesus quotes the Shema, calling for a love that includes the intellect.",
    reference: "Matthew 22:37",
  },
  {
    id: "love-5",
    fruit: "love",
    prompt: "Which question prompted Jesus to tell the parable of the Good Samaritan?",
    options: [
      "\u201CWho is the greatest?\u201D",
      "\u201CAnd who is my neighbour?\u201D",
      "\u201CHow often must I forgive?\u201D",
      "\u201CWhere do you live?\u201D",
    ],
    answer: 1,
    note: "An expert in the law asked it, wanting to justify himself \u2014 and got a story instead of a definition.",
    reference: "Luke 10:29",
  },
  {
    id: "love-6",
    fruit: "love",
    prompt: "\u201CLove your enemies and ___ for those who persecute you.\u201D",
    options: ["wait", "pray", "sing", "provide"],
    answer: 1,
    note: "From the Sermon on the Mount \u2014 love that reaches the people hardest to love.",
    reference: "Matthew 5:44",
  },
  {
    id: "love-7",
    fruit: "love",
    prompt: "Faith, hope and love remain \u2014 but which is the greatest?",
    options: ["Faith", "Hope", "Love", "They are equal"],
    answer: 2,
    note: "Faith and hope will one day be fulfilled; love never ends.",
    reference: "1 Corinthians 13:13",
  },
  {
    id: "love-8",
    fruit: "love",
    prompt: "By the shore after the resurrection, how many times did Jesus ask Peter \u201CDo you love me?\u201D",
    options: ["Once", "Twice", "Three times", "Seven times"],
    answer: 2,
    note: "Three questions for three denials \u2014 restoration, one charcoal fire at a time.",
    reference: "John 21:15-17",
  },
  {
    id: "love-9",
    fruit: "love",
    prompt: "\u201CAbove all, love each other deeply, because love covers over a ___ of sins.\u201D",
    options: ["multitude", "memory", "lifetime", "harvest"],
    answer: 0,
    note: "Peter echoes Proverbs 10:12 \u2014 love does not broadcast failure, it covers it.",
    reference: "1 Peter 4:8",
  },
  {
    id: "love-10",
    fruit: "love",
    prompt: "\u201CFor God so loved the world that he gave his one and only ___.\u201D",
    options: ["Son", "Word", "Law", "Kingdom"],
    answer: 0,
    note: "The measure of divine love is the size of the gift.",
    reference: "John 3:16",
  },

  /* ─────────────── JOY ─────────────── */
  {
    id: "joy-1",
    fruit: "joy",
    prompt: "\u201CThe joy of the LORD is your ___.\u201D",
    options: ["shield", "strength", "song", "portion"],
    answer: 1,
    note: "Nehemiah said it to a weeping people on the day the Law was read aloud again.",
    reference: "Nehemiah 8:10",
  },
  {
    id: "joy-2",
    fruit: "joy",
    prompt: "Who sang hymns at midnight while chained in a Philippian jail?",
    options: [
      "Peter and John",
      "Paul and Silas",
      "Barnabas and Mark",
      "Stephen and Philip",
    ],
    answer: 1,
    note: "The other prisoners were listening \u2014 then an earthquake opened every door.",
    reference: "Acts 16:25",
  },
  {
    id: "joy-3",
    fruit: "joy",
    prompt: "The angel told the shepherds: \u201CI bring you good news that will cause great joy for ___ the people.\u201D",
    options: ["all", "some of", "many of", "the chosen"],
    answer: 0,
    note: "The first Christmas announcement went to night-shift shepherds, for everyone.",
    reference: "Luke 2:10",
  },
  {
    id: "joy-4",
    fruit: "joy",
    prompt: "\u201CRejoice in the Lord always. I will say it again: ___!\u201D",
    options: ["Believe", "Rejoice", "Give thanks", "Stand firm"],
    answer: 1,
    note: "Written by Paul from prison \u2014 which is why the repetition lands so hard.",
    reference: "Philippians 4:4",
  },
  {
    id: "joy-5",
    fruit: "joy",
    prompt: "In Luke 15, what does the shepherd do when he finds the one lost sheep?",
    options: [
      "Scolds it and drives it home",
      "Joyfully lays it on his shoulders",
      "Leaves it for the morning",
      "Sells it at market",
    ],
    answer: 1,
    note: "Then he calls the neighbours together \u2014 heaven throws parties over the found.",
    reference: "Luke 15:5-6",
  },
  {
    id: "joy-6",
    fruit: "joy",
    prompt: "\u201CYou make known to me the path of life; in your presence there is fullness of ___.\u201D",
    options: ["light", "joy", "peace", "mercy"],
    answer: 1,
    note: "David locates joy geographically \u2014 it lives wherever God is.",
    reference: "Psalm 16:11",
  },
  {
    id: "joy-7",
    fruit: "joy",
    prompt: "Who leaped for joy in Elizabeth\u2019s womb at the sound of Mary\u2019s greeting?",
    options: ["Isaac", "Samuel", "John the Baptist", "James"],
    answer: 2,
    note: "The forerunner started his ministry before he was even born.",
    reference: "Luke 1:41-44",
  },
  {
    id: "joy-8",
    fruit: "joy",
    prompt: "\u201CConsider it pure joy... whenever you face ___ of many kinds.\u201D",
    options: ["trials", "questions", "journeys", "seasons"],
    answer: 0,
    note: "James is not celebrating the trial \u2014 he is celebrating what perseverance produces.",
    reference: "James 1:2",
  },
  {
    id: "joy-9",
    fruit: "joy",
    prompt: "\u201CWeeping may stay for the night, but ___ comes in the morning.\u201D",
    options: ["rescue", "rejoicing", "light", "the harvest"],
    answer: 1,
    note: "Sorrow is a lodger, not a landlord.",
    reference: "Psalm 30:5",
  },

  /* ─────────────── PEACE ─────────────── */
  {
    id: "peace-1",
    fruit: "peace",
    prompt: "\u201CBlessed are the peacemakers, for they will be called ___ of God.\u201D",
    options: ["friends", "children", "servants", "heirs"],
    answer: 1,
    note: "Peacemaking is family resemblance \u2014 it shows whose you are.",
    reference: "Matthew 5:9",
  },
  {
    id: "peace-2",
    fruit: "peace",
    prompt: "What did Jesus say to the storm on the Sea of Galilee?",
    options: [
      "\u201CQuiet! Be still!\u201D",
      "\u201CGo in peace.\u201D",
      "\u201CDo not be afraid.\u201D",
      "\u201CIt is finished.\u201D",
    ],
    answer: 0,
    note: "He rebuked the wind, and there was a complete calm \u2014 outside the boat and inside it.",
    reference: "Mark 4:39",
  },
  {
    id: "peace-3",
    fruit: "peace",
    prompt: "Isaiah names the coming Messiah Wonderful Counsellor, Mighty God, Everlasting Father and ___.",
    options: [
      "Prince of Peace",
      "King of Glory",
      "Lion of Judah",
      "Bright Morning Star",
    ],
    answer: 0,
    note: "Written seven centuries before the manger.",
    reference: "Isaiah 9:6",
  },
  {
    id: "peace-4",
    fruit: "peace",
    prompt: "Which bird returned to Noah carrying a freshly plucked olive leaf?",
    options: ["A raven", "A dove", "A sparrow", "An eagle"],
    answer: 1,
    note: "The oldest peace symbol in the world came out of a floating window.",
    reference: "Genesis 8:11",
  },
  {
    id: "peace-5",
    fruit: "peace",
    prompt: "The peace of God \u201Ctranscends all understanding\u201D and guards your hearts and your ___.",
    options: ["homes", "minds", "steps", "hands"],
    answer: 1,
    note: "The verb is military \u2014 peace stands sentry over anxious thoughts.",
    reference: "Philippians 4:7",
  },
  {
    id: "peace-6",
    fruit: "peace",
    prompt: "\u201CMy peace I give you. I do not give to you as the ___ gives.\u201D",
    options: ["world", "temple", "law", "king"],
    answer: 0,
    note: "The world's peace depends on the absence of trouble; His does not.",
    reference: "John 14:27",
  },
  {
    id: "peace-7",
    fruit: "peace",
    prompt: "Which Hebrew word for peace means completeness, wholeness and well-being?",
    options: ["Hesed", "Shalom", "Ruach", "Selah"],
    answer: 1,
    note: "Shalom is far bigger than quiet \u2014 it is everything as it should be.",
    reference: "Numbers 6:26",
  },
  {
    id: "peace-8",
    fruit: "peace",
    prompt: "\u201CTherefore, since we have been justified through faith, we have peace with God through ___.\u201D",
    options: [
      "our good works",
      "the prophets",
      "our Lord Jesus Christ",
      "the temple sacrifices",
    ],
    answer: 2,
    note: "Peace with God comes first; the peace of God follows.",
    reference: "Romans 5:1",
  },
  {
    id: "peace-9",
    fruit: "peace",
    prompt: "\u201CYou will keep in perfect peace those whose minds are ___ on you.\u201D",
    options: ["steadfast", "humbled", "opened", "turned"],
    answer: 0,
    note: "Literally 'leaning' on God \u2014 peace is a posture before it is a feeling.",
    reference: "Isaiah 26:3",
  },

  /* ─────────────── PATIENCE ─────────────── */
  {
    id: "longsuffering-1",
    fruit: "longsuffering",
    prompt: "Whose perseverance through suffering does James hold up as the great example?",
    options: ["Job", "Jonah", "Jeremiah", "Joshua"],
    answer: 0,
    note: "\u201CYou have heard of Job\u2019s perseverance and have seen what the Lord finally brought about.\u201D",
    reference: "James 5:11",
  },
  {
    id: "longsuffering-2",
    fruit: "longsuffering",
    prompt: "How many years in total did Jacob work in order to marry Rachel?",
    options: ["7", "12", "14", "21"],
    answer: 2,
    note: "Seven years, a wedding-night switch, then seven more \u2014 and they seemed like only a few days to him.",
    reference: "Genesis 29:20-30",
  },
  {
    id: "longsuffering-3",
    fruit: "longsuffering",
    prompt: "\u201CBe joyful in hope, patient in ___, faithful in prayer.\u201D",
    options: ["waiting", "affliction", "service", "poverty"],
    answer: 1,
    note: "Three habits Paul stacks together in a single breath.",
    reference: "Romans 12:12",
  },
  {
    id: "longsuffering-4",
    fruit: "longsuffering",
    prompt: "How many years did Israel wander in the wilderness before entering the promised land?",
    options: ["7", "12", "40", "70"],
    answer: 2,
    note: "One year for each day the spies explored the land they were afraid to take.",
    reference: "Numbers 14:34",
  },
  {
    id: "longsuffering-5",
    fruit: "longsuffering",
    prompt: "James compares longsuffering to a farmer waiting for what?",
    options: [
      "The autumn and spring rains",
      "The stars to appear",
      "The king\u2019s decree",
      "The city gates to open",
    ],
    answer: 0,
    note: "You cannot rush a crop. You can only stay in the field.",
    reference: "James 5:7",
  },
  {
    id: "longsuffering-6",
    fruit: "longsuffering",
    prompt: "Roughly how old was Abraham when the promised son Isaac was finally born?",
    options: ["75", "86", "100", "120"],
    answer: 2,
    note: "Twenty-five years passed between the promise and the laughter.",
    reference: "Genesis 21:5",
  },
  {
    id: "longsuffering-7",
    fruit: "longsuffering",
    prompt: "\u201CThose who hope in the LORD will renew their strength. They will soar on wings like ___.\u201D",
    options: ["doves", "eagles", "ravens", "swallows"],
    answer: 1,
    note: "The reward for waiting is not exhaustion but altitude.",
    reference: "Isaiah 40:31",
  },
  {
    id: "longsuffering-8",
    fruit: "longsuffering",
    prompt: "Which fruit tree does Jesus use in a parable about giving one more year of longsuffering?",
    options: ["Olive tree", "Fig tree", "Vine", "Mustard tree"],
    answer: 1,
    note: "\u201CLeave it alone for one more year, and I\u2019ll dig around it and fertilise it.\u201D",
    reference: "Luke 13:6-9",
  },
  {
    id: "longsuffering-9",
    fruit: "longsuffering",
    prompt: "\u201CThe Lord is not slow in keeping his promise... he is ___ with you.\u201D",
    options: ["patient", "pleased", "gentle", "honest"],
    answer: 0,
    note: "What looks like divine delay is actually divine longsuffering, making room for repentance.",
    reference: "2 Peter 3:9",
  },

  /* ─────────────── KINDNESS ─────────────── */
  {
    id: "gentleness-1",
    fruit: "gentleness",
    prompt: "\u201CBe kind and compassionate to one another, forgiving each other\u201D appears in which letter?",
    options: ["Ephesians", "Colossians", "Hebrews", "1 Peter"],
    answer: 0,
    note: "The standard is set in the second half: \u201Cjust as in Christ God forgave you.\u201D",
    reference: "Ephesians 4:32",
  },
  {
    id: "gentleness-2",
    fruit: "gentleness",
    prompt: "Which king searched for someone from Saul\u2019s family to show gentleness to, and found Mephibosheth?",
    options: ["Solomon", "David", "Hezekiah", "Josiah"],
    answer: 1,
    note: "He did it \u201Cfor Jonathan\u2019s sake\u201D \u2014 and gave him a permanent seat at the king\u2019s table.",
    reference: "2 Samuel 9:1-7",
  },
  {
    id: "gentleness-3",
    fruit: "gentleness",
    prompt: "Who stopped for the wounded traveller on the road down to Jericho?",
    options: ["A priest", "A Levite", "A Samaritan", "A tax collector"],
    answer: 2,
    note: "The one least expected to help paid for the room and promised to return.",
    reference: "Luke 10:33-35",
  },
  {
    id: "gentleness-4",
    fruit: "gentleness",
    prompt: "Which woman refused to abandon her widowed mother-in-law Naomi?",
    options: ["Orpah", "Ruth", "Hannah", "Abigail"],
    answer: 1,
    note: "\u201CWhere you go I will go, and where you stay I will stay.\u201D",
    reference: "Ruth 1:16",
  },
  {
    id: "gentleness-5",
    fruit: "gentleness",
    prompt: "Who told his harvesters to deliberately leave extra grain for Ruth to gather?",
    options: ["Boaz", "Elimelek", "Obed", "Jesse"],
    answer: 0,
    note: "Gentleness dressed as agriculture \u2014 and it ended in a marriage.",
    reference: "Ruth 2:15-16",
  },
  {
    id: "gentleness-6",
    fruit: "gentleness",
    prompt: "\u201CWhoever is kind to the poor lends to the ___.\u201D",
    options: ["LORD", "city", "elders", "future"],
    answer: 0,
    note: "\u201C...and he will reward them for what they have done.\u201D God treats it as a personal loan.",
    reference: "Proverbs 19:17",
  },
  {
    id: "gentleness-7",
    fruit: "gentleness",
    prompt: "The widow of Zarephath shared her last flour and oil with which prophet?",
    options: ["Elisha", "Elijah", "Samuel", "Nathan"],
    answer: 1,
    note: "Her jar did not run dry through the whole famine.",
    reference: "1 Kings 17:8-16",
  },
  {
    id: "gentleness-8",
    fruit: "gentleness",
    prompt: "\u201CGod\u2019s gentleness is intended to lead you to ___.\u201D",
    options: ["repentance", "wisdom", "obedience", "worship"],
    answer: 0,
    note: "Paul warns against treating divine longsuffering as divine indifference.",
    reference: "Romans 2:4",
  },
  {
    id: "gentleness-9",
    fruit: "gentleness",
    prompt: "In Acts 28, the islanders of Malta showed Paul \u201Cunusual gentleness\u201D by doing what?",
    options: [
      "Building him a boat",
      "Building a fire and welcoming them",
      "Paying his passage to Rome",
      "Returning his belongings",
    ],
    answer: 1,
    note: "It was raining and cold, and a shipwrecked prisoner was made welcome.",
    reference: "Acts 28:2",
  },

  /* ─────────────── GOODNESS ─────────────── */
  {
    id: "goodness-1",
    fruit: "goodness",
    prompt: "\u201CSurely your goodness and ___ will follow me all the days of my life.\u201D",
    options: ["mercy", "light", "peace", "justice"],
    answer: 0,
    note: "The Hebrew verb is closer to 'pursue' \u2014 goodness chases the shepherd's sheep.",
    reference: "Psalm 23:6",
  },
  {
    id: "goodness-2",
    fruit: "goodness",
    prompt: "After the sixth day of creation, God saw all that He had made and it was...",
    options: ["good", "very good", "finished", "at rest"],
    answer: 1,
    note: "Six days were 'good'. Only the whole, with people in it, was 'very good'.",
    reference: "Genesis 1:31",
  },
  {
    id: "goodness-3",
    fruit: "goodness",
    prompt: "Peter summarised Jesus\u2019 ministry as: \u201CHe went around doing ___ and healing all.\u201D",
    options: ["good", "wonders", "justice", "mercy"],
    answer: 0,
    note: "The shortest biography of Christ ever written.",
    reference: "Acts 10:38",
  },
  {
    id: "goodness-4",
    fruit: "goodness",
    prompt: "\u201CDo not be overcome by evil, but overcome evil with ___.\u201D",
    options: ["good", "truth", "prayer", "silence"],
    answer: 0,
    note: "Paul's strategy for enemies: feed them.",
    reference: "Romans 12:21",
  },
  {
    id: "goodness-5",
    fruit: "goodness",
    prompt: "\u201CTaste and see that the LORD is ___.\u201D",
    options: ["near", "good", "holy", "faithful"],
    answer: 1,
    note: "An invitation to experiment, not merely to agree.",
    reference: "Psalm 34:8",
  },
  {
    id: "goodness-6",
    fruit: "goodness",
    prompt: "To whom did Jesus say, \u201CNo one is good \u2014 except God alone\u201D?",
    options: [
      "Nicodemus",
      "The rich young ruler",
      "Zacchaeus",
      "The Samaritan woman",
    ],
    answer: 1,
    note: "The man had greeted him as \u201Cgood teacher\u201D, and Jesus went straight for the word 'good'.",
    reference: "Mark 10:18",
  },
  {
    id: "goodness-7",
    fruit: "goodness",
    prompt: "\u201CLet us not become weary in doing good, for at the proper time we will reap a ___.\u201D",
    options: ["reward", "harvest", "crown", "blessing"],
    answer: 1,
    note: "\u201C...if we do not give up.\u201D The condition is stamina.",
    reference: "Galatians 6:9",
  },
  {
    id: "goodness-8",
    fruit: "goodness",
    prompt: "Who is described in Acts as \u201Ca good man, full of the Holy Spirit and faith\u201D?",
    options: ["Stephen", "Barnabas", "Cornelius", "Apollos"],
    answer: 1,
    note: "His name means 'son of encouragement', and he vouched for Saul when nobody else would.",
    reference: "Acts 11:24",
  },
  {
    id: "goodness-9",
    fruit: "goodness",
    prompt: "Micah 6:8 \u2014 what does the LORD require? To act justly, love mercy and ___ with your God.",
    options: [
      "walk humbly",
      "sing gladly",
      "stand firmly",
      "labour faithfully",
    ],
    answer: 0,
    note: "Three lines that summarise the whole prophetic tradition.",
    reference: "Micah 6:8",
  },

  /* ─────────────── FAITHFULNESS ─────────────── */
  {
    id: "faith-1",
    fruit: "faith",
    prompt: "\u201CThey are new every morning; great is your ___.\u201D",
    options: ["mercy", "faith", "gentleness", "glory"],
    answer: 1,
    note: "Written in the ruins of Jerusalem \u2014 the boldest sentence in Lamentations.",
    reference: "Lamentations 3:23",
  },
  {
    id: "faith-2",
    fruit: "faith",
    prompt: "Who kept praying three times a day at an open window, knowing it meant the lions\u2019 den?",
    options: ["Daniel", "Nehemiah", "Ezra", "Mordecai"],
    answer: 0,
    note: "He did not pray louder or quieter. He prayed \u201Cjust as he had done before.\u201D",
    reference: "Daniel 6:10",
  },
  {
    id: "faith-3",
    fruit: "faith",
    prompt: "Which three men refused to bow to Nebuchadnezzar\u2019s golden statue?",
    options: [
      "Shadrach, Meshach and Abednego",
      "Hananiah, Azariah and Daniel",
      "Peter, James and John",
      "Joshua, Caleb and Eleazar",
    ],
    answer: 0,
    note: "\u201CBut even if he does not\u2026\u201D \u2014 faith without a guarantee.",
    reference: "Daniel 3:16-18",
  },
  {
    id: "faith-4",
    fruit: "faith",
    prompt: "In the parable of the talents, the master says: \u201CWell done, good and faithful ___!\u201D",
    options: ["friend", "servant", "steward", "son"],
    answer: 1,
    note: "\u201CYou have been faithful with a few things; I will put you in charge of many things.\u201D",
    reference: "Matthew 25:21",
  },
  {
    id: "faith-5",
    fruit: "faith",
    prompt: "Hebrews 3 says who was \u201Cfaithful in all God\u2019s house as a servant\u201D?",
    options: ["Abraham", "Moses", "Aaron", "Samuel"],
    answer: 1,
    note: "Faithful as a servant in the house \u2014 while Christ is faithful as the Son over it.",
    reference: "Hebrews 3:5",
  },
  {
    id: "faith-6",
    fruit: "faith",
    prompt: "\u201CIf we are faithless, he remains faithful, for he cannot ___ himself.\u201D",
    options: ["disown", "forget", "divide", "humble"],
    answer: 0,
    note: "God's faith is anchored in His own nature, not in our performance.",
    reference: "2 Timothy 2:13",
  },
  {
    id: "faith-7",
    fruit: "faith",
    prompt: "\u201CBe faithful, even to the point of death, and I will give you the ___ of life.\u201D",
    options: ["book", "water", "crown", "tree"],
    answer: 2,
    note: "Spoken to the persecuted church in Smyrna.",
    reference: "Revelation 2:10",
  },
  {
    id: "faith-8",
    fruit: "faith",
    prompt: "Which prophet stayed faithful for forty years while almost nobody listened?",
    options: ["Jeremiah", "Obadiah", "Haggai", "Nahum"],
    answer: 0,
    note: "The weeping prophet preached to a city that jailed him for it \u2014 and kept preaching.",
    reference: "Jeremiah 1:5; 20:9",
  },
  {
    id: "faith-9",
    fruit: "faith",
    prompt: "\u201CNow it is required that those who have been given a trust must prove ___.\u201D",
    options: ["wise", "faithful", "bold", "diligent"],
    answer: 1,
    note: "Paul's job description for anyone entrusted with anything.",
    reference: "1 Corinthians 4:2",
  },

  /* ─────────────── GENTLENESS ─────────────── */
  {
    id: "gentle-1",
    fruit: "meekness",
    prompt: "\u201CTake my yoke upon you and learn from me, for I am gentle and ___ in heart.\u201D",
    options: ["humble", "pure", "patient", "steady"],
    answer: 0,
    note: "The only place Jesus describes His own heart \u2014 and this is the word He chooses.",
    reference: "Matthew 11:29",
  },
  {
    id: "gentle-2",
    fruit: "meekness",
    prompt: "\u201CLet your meekness be evident to ___. The Lord is near.\u201D",
    options: ["all", "the church", "your household", "the elders"],
    answer: 0,
    note: "Not just to the easy people. To all.",
    reference: "Philippians 4:5",
  },
  {
    id: "gentle-3",
    fruit: "meekness",
    prompt: "\u201CA gentle answer turns away wrath, but a harsh word stirs up ___.\u201D",
    options: ["anger", "envy", "strife", "folly"],
    answer: 0,
    note: "The whole book of Proverbs in one lever: tone changes outcomes.",
    reference: "Proverbs 15:1",
  },
  {
    id: "gentle-4",
    fruit: "meekness",
    prompt: "On Mount Horeb, where did Elijah finally hear the LORD?",
    options: [
      "In the great wind",
      "In the earthquake",
      "In the fire",
      "In a gentle whisper",
    ],
    answer: 3,
    note: "The God who splits mountains chose to speak in a low murmur.",
    reference: "1 Kings 19:11-12",
  },
  {
    id: "gentle-5",
    fruit: "meekness",
    prompt: "\u201CBlessed are the ___, for they will inherit the earth.\u201D",
    options: ["meek", "poor", "pure", "merciful"],
    answer: 0,
    note: "Meekness is not weakness \u2014 it is strength that has learned restraint.",
    reference: "Matthew 5:5",
  },
  {
    id: "gentle-6",
    fruit: "meekness",
    prompt: "Fulfilling Zechariah\u2019s prophecy, Jesus entered Jerusalem riding on what?",
    options: ["A war horse", "A donkey\u2019s colt", "A chariot", "He walked"],
    answer: 1,
    note: "\u201CSee, your king comes to you, gentle and riding on a donkey.\u201D",
    reference: "Matthew 21:5",
  },
  {
    id: "gentle-7",
    fruit: "meekness",
    prompt: "Give the reason for your hope \u201Cwith meekness and ___.\u201D",
    options: ["respect", "boldness", "clarity", "longsuffering"],
    answer: 0,
    note: "How you say it is part of what you are saying.",
    reference: "1 Peter 3:15",
  },
  {
    id: "gentle-8",
    fruit: "meekness",
    prompt: "Who is described as \u201Cmore humble than anyone else on the face of the earth\u201D?",
    options: ["Job", "Moses", "David", "Enoch"],
    answer: 1,
    note: "The man who confronted Pharaoh was also the gentlest man alive.",
    reference: "Numbers 12:3",
  },
  {
    id: "gentle-9",
    fruit: "meekness",
    prompt: "Isaiah says of the Servant: \u201CA bruised reed he will not break, a ___ wick he will not snuff out.\u201D",
    options: ["smouldering", "fallen", "dying", "flickering"],
    answer: 0,
    note: "He handles the barely-holding-on with extraordinary care.",
    reference: "Isaiah 42:3",
  },

  /* ─────────────── SELF-CONTROL ─────────────── */
  {
    id: "self-1",
    fruit: "temperance",
    prompt: "\u201CLike a city whose ___ are broken through is a person who lacks temperance.\u201D",
    options: ["gates", "walls", "towers", "wells"],
    answer: 1,
    note: "No walls means anything at all can walk in.",
    reference: "Proverbs 25:28",
  },
  {
    id: "self-2",
    fruit: "temperance",
    prompt: "How many days did Jesus fast in the wilderness before He was tempted?",
    options: ["3", "7", "40", "70"],
    answer: 2,
    note: "He answered every temptation with Scripture, at His physically weakest.",
    reference: "Matthew 4:2",
  },
  {
    id: "self-3",
    fruit: "temperance",
    prompt: "Which judge lost his strength after giving away the secret of his uncut hair?",
    options: ["Gideon", "Jephthah", "Samson", "Ehud"],
    answer: 2,
    note: "Enormous strength, almost no self-mastery \u2014 a cautionary tale in one man.",
    reference: "Judges 16:17-19",
  },
  {
    id: "self-4",
    fruit: "temperance",
    prompt: "Paul says athletes go into strict training for a crown that will not ___.",
    options: ["last", "shine", "fit", "return"],
    answer: 0,
    note: "\u201CI strike a blow to my body and make it my slave.\u201D Training language, on purpose.",
    reference: "1 Corinthians 9:25-27",
  },
  {
    id: "self-5",
    fruit: "temperance",
    prompt: "Who ran out of the house, leaving his cloak behind, rather than sin with Potiphar\u2019s wife?",
    options: ["Joseph", "Daniel", "Benjamin", "Judah"],
    answer: 0,
    note: "Temperance sometimes looks like sprinting.",
    reference: "Genesis 39:12",
  },
  {
    id: "self-6",
    fruit: "temperance",
    prompt: "What did Esau trade his birthright for?",
    options: [
      "A field",
      "A bowl of stew",
      "A herd of goats",
      "A wife from Canaan",
    ],
    answer: 1,
    note: "Red lentil stew, one hungry afternoon, and a lifetime of regret.",
    reference: "Genesis 25:29-34",
  },
  {
    id: "self-7",
    fruit: "temperance",
    prompt: "Grace teaches us to say \u201CNo\u201D to ungodliness and to live temperanceled, upright and ___ lives.",
    options: ["godly", "quiet", "generous", "joyful"],
    answer: 0,
    note: "Grace is not permission to drift; it is a teacher with a curriculum.",
    reference: "Titus 2:12",
  },
  {
    id: "self-8",
    fruit: "temperance",
    prompt: "\u201CBe alert and of sober mind. Your enemy the devil prowls around like a roaring ___.\u201D",
    options: ["lion", "wolf", "bear", "serpent"],
    answer: 0,
    note: "Sobriety and vigilance are named as defences before courage is.",
    reference: "1 Peter 5:8",
  },
  {
    id: "self-9",
    fruit: "temperance",
    prompt: "\u201CEveryone should be quick to listen, slow to speak and slow to become ___.\u201D",
    options: ["angry", "weary", "proud", "afraid"],
    answer: 0,
    note: "Two ears, one mouth, and a deliberately slow temper.",
    reference: "James 1:19",
  },

  /* ─────────────── HARVEST (general) ─────────────── */
  {
    id: "harvest-1",
    fruit: "harvest",
    prompt: "In which chapter is the fruit of the Spirit listed?",
    options: ["Romans 8", "Galatians 5", "Ephesians 6", "Colossians 3"],
    answer: 1,
    note: "Paul sets it directly against the 'acts of the flesh' listed a few verses earlier.",
    reference: "Galatians 5:22-23",
  },
  {
    id: "harvest-2",
    fruit: "harvest",
    prompt: "How many qualities are named in the fruit of the Spirit?",
    options: ["Seven", "Eight", "Nine", "Twelve"],
    answer: 2,
    note: "Nine qualities \u2014 but 'fruit' is singular. One fruit, nine flavours.",
    reference: "Galatians 5:22-23",
  },
  {
    id: "harvest-3",
    fruit: "harvest",
    prompt: "Which quality completes the list: love, joy, peace, longsuffering, gentleness, goodness, faith, meekness and ___?",
    options: ["wisdom", "temperance", "courage", "humility"],
    answer: 1,
    note: "Temperance brings up the rear \u2014 and holds the other eight together.",
    reference: "Galatians 5:23",
  },
  {
    id: "harvest-4",
    fruit: "harvest",
    prompt: "Which of these is NOT listed as a fruit of the Spirit?",
    options: ["Goodness", "Meekness", "Knowledge", "Faith"],
    answer: 2,
    note: "Knowledge appears in Peter's list of virtues, but not in Galatians 5.",
    reference: "Galatians 5:22-23",
  },
  {
    id: "harvest-5",
    fruit: "harvest",
    prompt: "\u201CAgainst such things there is no ___.\u201D",
    options: ["law", "end", "shame", "rival"],
    answer: 0,
    note: "Paul's dry punchline: nobody ever passed a law against gentleness.",
    reference: "Galatians 5:23",
  },
  {
    id: "harvest-6",
    fruit: "harvest",
    prompt: "Who wrote the letter to the churches in Galatia?",
    options: ["Peter", "Paul", "John", "James"],
    answer: 1,
    note: "He wrote it in large letters with his own hand at the end.",
    reference: "Galatians 6:11",
  },
  {
    id: "harvest-7",
    fruit: "harvest",
    prompt: "\u201CI am the vine; you are the ___.\u201D",
    options: ["branches", "harvest", "gardeners", "soil"],
    answer: 0,
    note: "\u201CApart from me you can do nothing.\u201D Fruit is a by-product of connection.",
    reference: "John 15:5",
  },
  {
    id: "harvest-8",
    fruit: "harvest",
    prompt: "\u201CBy their ___ you will recognise them.\u201D",
    options: ["words", "fruit", "robes", "prayers"],
    answer: 1,
    note: "Jesus' test for true and false teachers is agricultural, not verbal.",
    reference: "Matthew 7:16",
  },
  {
    id: "harvest-9",
    fruit: "harvest",
    prompt: "What does Paul call the list of behaviours contrasted with the fruit of the Spirit?",
    options: [
      "The acts of the flesh",
      "The works of the night",
      "The ways of Egypt",
      "The counsel of fools",
    ],
    answer: 0,
    note: "Galatians 5:19-21 lists them just before the beautiful nine.",
    reference: "Galatians 5:19",
  },
  {
    id: "harvest-10",
    fruit: "harvest",
    prompt: "Which quality is listed first?",
    options: ["Joy", "Peace", "Love", "Faith"],
    answer: 2,
    note: "Love leads, and many read the other eight as descriptions of what love looks like.",
    reference: "Galatians 5:22",
  },
  {
    id: "harvest-11",
    fruit: "harvest",
    prompt: "Which quality comes immediately after peace in the list?",
    options: ["Gentleness", "Longsuffering", "Goodness", "Meekness"],
    answer: 1,
    note: "Love, joy, peace \u2014 then longsuffering turns the list outward toward other people.",
    reference: "Galatians 5:22",
  },
  {
    id: "harvest-12",
    fruit: "harvest",
    prompt: "Psalm 1 compares the blessed person to a tree planted by streams of water that yields fruit in ___.",
    options: ["season", "silence", "abundance", "the morning"],
    answer: 0,
    note: "\u201C...and whose leaf does not wither.\u201D Rooted things ripen on time.",
    reference: "Psalm 1:3",
  },
  {
    id: "harvest-13",
    fruit: "harvest",
    prompt: "\u201CSo I say, walk by the Spirit, and you will not gratify the desires of the ___.\u201D",
    options: ["flesh", "world", "eyes", "heart"],
    answer: 0,
    note: "The command is not 'try harder' \u2014 it is 'walk by the Spirit'.",
    reference: "Galatians 5:16",
  },
  {
    id: "harvest-14",
    fruit: "harvest",
    prompt: "In the parable of the sower, the seed on good soil produces a crop of how much?",
    options: [
      "Ten, twenty or thirty times",
      "Thirty, sixty or a hundred times",
      "Twice what was sown",
      "A full measure each time",
    ],
    answer: 1,
    note: "Same seed, same sower \u2014 the variable is the soil.",
    reference: "Matthew 13:8",
  },
];

export function shuffle<T>(items: T[]): T[] {
  const copy = [...items];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

export const QUESTIONS_PER_ROUND = 8;
export const HARVEST_ROUND_SIZE = 12;

const BY_ID = new Map(QUESTIONS.map((q) => [q.id, q]));

/** Resolve a frozen, ordered id list back into questions (skips unknown ids). */
export function getQuestionsByIds(ids: string[]): Question[] {
  return ids.map((id) => BY_ID.get(id)).filter((q): q is Question => !!q);
}

export function buildRound(round: RoundId): Question[] {
  if (round === "harvest") {
    const general = shuffle(QUESTIONS.filter((q) => q.fruit === "harvest")).slice(
      0,
      6,
    );
    const perFruit = shuffle(QUESTIONS.filter((q) => q.fruit !== "harvest")).slice(
      0,
      HARVEST_ROUND_SIZE - general.length,
    );
    return shuffle([...general, ...perFruit]);
  }
  return shuffle(QUESTIONS.filter((q) => q.fruit === round)).slice(
    0,
    QUESTIONS_PER_ROUND,
  );
}
